spring:
  application:
    name: concert-ticketing
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_new_id_generator_mappings: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 600000 # Cach

  swagger-ui:
    path: /api-test
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match:
    - /api/**

logging:
  level:
    com.hhplus.concertticketing: INFO

management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: health,info,metrics,prometheus