spring:
  application:
    name: concert-ticketing
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트 시 데이터베이스를 초기화하기 위해 사용
    properties:
      hibernate:
        use_new_id_generator_mappings: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: none  # 테스트에서 Redis 캐시 사용하지 않도록 설정

  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: concert-ticketing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  swagger-ui:
    path: /api-test
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match:
    - /api/**

logging:
  level:
    com.hhplus.concertticketing: INFO

management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: health,info,metrics,prometheus

payment_topic: PAYMENT-INFO